// src/Sidebar.jsx
import React from 'react';
import './Sidebar.css'; // Importando o arquivo CSS para estilização

const Sidebar = ({ handleRectangleClick, clickedCategory }) => {
  return (
    <div className="sidebar-container">
      <div className="sidebar-menu">
        <div className="sidebar-overlap-group">
          <div className="sidebar-image"><img className="sidebar-logo" src="/assets/logo-grupo.png" alt="Logo do Grupo" /></div>
          <div className="sidebar-overlap">
            {/* Emitir evento com categoria 'Canteiro' quando clicado */}
            <div
              className={`sidebar-rectangle ${clickedCategory === 'Canteiro' ? 'clicked' : ''}`}
              onClick={() => handleRectangleClick('Canteiro')}
            ></div>
            <div className="sidebar-text-wrapper">Canteiro</div>
          </div>
          <div className="sidebar-divider"></div>
          <div className="sidebar-overlap">
            {/* Emitir evento com categoria 'Contabilidade' quando clicado */}
            <div
              className={`sidebar-rectangle ${clickedCategory === 'Contabilidade' ? 'clicked' : ''}`}
              onClick={() => handleRectangleClick('Contabilidade')}
            ></div>
            <div className="sidebar-text-wrapper-2">Contabilidade</div>
          </div>
          <div className="sidebar-divider"></div>
          <div className="sidebar-overlap-2">
            {/* Emitir evento com categoria 'Fiscal' quando clicado */}
            <div
              className={`sidebar-rectangle ${clickedCategory === 'Fiscal' ? 'clicked' : ''}`}
              onClick={() => handleRectangleClick('Fiscal')}
            ></div>
            <div className="sidebar-text-wrapper-3">Fiscal</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Sidebar;

// frontEnd/src/app/components/side-bar/side-bar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-side-bar',
  templateUrl: './side-bar.component.html',
  styleUrl: './side-bar.component.scss'
})
export class SideBarComponent {
  clickedCategory: string | null = null;

  handleRectangleClick(category: string): void {
    // Se a categoria clicada for a mesma que a já clicada, remova a classe 'clicked'
    if (this.clickedCategory === category) {
      this.clickedCategory = null;
    } else {
      // Caso contrário, atualize a categoria clicada
      this.clickedCategory = category;
    }
    console.log(this.clickedCategory)

    // Adicione aqui o código que você deseja executar quando o retângulo for clicado
  }
}

<div class="box">
    <div class="menu-lateral">
        <div class="overlap-group">
            <div class="image"><img class="logo-grupo" src="/assets/logo-grupo.png" /></div>
            <div class="overlap">
                <!-- Emitir evento com categoria 'Canteiro' quando clicado -->
                <div class="rectangle" (click)="handleRectangleClick('Canteiro')"
                    [class.clicked]="clickedCategory === 'Canteiro'"></div>
                <div class="text-wrapper">Canteiro</div>
            </div>
            <div class="div">
                <!-- Emitir evento com categoria 'Contabilidade' quando clicado -->
                <div class="rectangle" (click)="handleRectangleClick('Contabilidade')"
                    [class.clicked]="clickedCategory === 'Contabilidade'"></div>
                <div class="text-wrapper-2">Contabilidade</div>
            </div>
            <div class="overlap-2">
                <!-- Emitir evento com categoria 'Fiscal' quando clicado -->
                <div class="rectangle" (click)="handleRectangleClick('Fiscal')"
                    [class.clicked]="clickedCategory === 'Fiscal'"></div>
                <div class="text-wrapper-3">Fiscal</div>
            </div>
        </div>
    </div>
</div>
